/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProductStockService } from "../productStock.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProductStockCreateInput } from "./ProductStockCreateInput";
import { ProductStockWhereInput } from "./ProductStockWhereInput";
import { ProductStockWhereUniqueInput } from "./ProductStockWhereUniqueInput";
import { ProductStockFindManyArgs } from "./ProductStockFindManyArgs";
import { ProductStockUpdateInput } from "./ProductStockUpdateInput";
import { ProductStock } from "./ProductStock";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProductStockControllerBase {
  constructor(
    protected readonly service: ProductStockService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProductStock",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProductStock })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: ProductStockCreateInput
  ): Promise<ProductStock> {
    return await this.service.create({
      data: {
        ...data,

        jobsite: data.jobsite
          ? {
              connect: data.jobsite,
            }
          : undefined,

        product: {
          connect: data.product,
        },

        warehouse: data.warehouse
          ? {
              connect: data.warehouse,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        itemCount: true,

        jobsite: {
          select: {
            id: true,
          },
        },

        product: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        warehouse: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProductStock",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProductStock] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ProductStockFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<ProductStock[]> {
    const args = plainToClass(ProductStockFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        itemCount: true,

        jobsite: {
          select: {
            id: true,
          },
        },

        product: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        warehouse: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProductStock",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProductStock })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ProductStockWhereUniqueInput
  ): Promise<ProductStock | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        itemCount: true,

        jobsite: {
          select: {
            id: true,
          },
        },

        product: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        warehouse: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProductStock",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProductStock })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ProductStockWhereUniqueInput,
    @common.Body() data: ProductStockUpdateInput
  ): Promise<ProductStock | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          jobsite: data.jobsite
            ? {
                connect: data.jobsite,
              }
            : undefined,

          product: {
            connect: data.product,
          },

          warehouse: data.warehouse
            ? {
                connect: data.warehouse,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          itemCount: true,

          jobsite: {
            select: {
              id: true,
            },
          },

          product: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          warehouse: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "ProductStock",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProductStock })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ProductStockWhereUniqueInput
  ): Promise<ProductStock | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          itemCount: true,

          jobsite: {
            select: {
              id: true,
            },
          },

          product: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          warehouse: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
