/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProductOrderService } from "../productOrder.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProductOrderCreateInput } from "./ProductOrderCreateInput";
import { ProductOrderWhereInput } from "./ProductOrderWhereInput";
import { ProductOrderWhereUniqueInput } from "./ProductOrderWhereUniqueInput";
import { ProductOrderFindManyArgs } from "./ProductOrderFindManyArgs";
import { ProductOrderUpdateInput } from "./ProductOrderUpdateInput";
import { ProductOrder } from "./ProductOrder";
import { OrderTrackFindManyArgs } from "../../orderTrack/base/OrderTrackFindManyArgs";
import { OrderTrack } from "../../orderTrack/base/OrderTrack";
import { OrderTrackWhereUniqueInput } from "../../orderTrack/base/OrderTrackWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProductOrderControllerBase {
  constructor(
    protected readonly service: ProductOrderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProductOrder",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProductOrder })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: ProductOrderCreateInput
  ): Promise<ProductOrder> {
    return await this.service.create({
      data: {
        ...data,

        jobsite: data.jobsite
          ? {
              connect: data.jobsite,
            }
          : undefined,

        order: data.order
          ? {
              connect: data.order,
            }
          : undefined,

        product: data.product
          ? {
              connect: data.product,
            }
          : undefined,

        supplier: data.supplier
          ? {
              connect: data.supplier,
            }
          : undefined,

        warehouse: data.warehouse
          ? {
              connect: data.warehouse,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        itemCount: true,

        jobsite: {
          select: {
            id: true,
          },
        },

        order: {
          select: {
            id: true,
          },
        },

        product: {
          select: {
            id: true,
          },
        },

        rentPrice: true,
        sourcedFrom: true,

        supplier: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        warehouse: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProductOrder",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProductOrder] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ProductOrderFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<ProductOrder[]> {
    const args = plainToClass(ProductOrderFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        itemCount: true,

        jobsite: {
          select: {
            id: true,
          },
        },

        order: {
          select: {
            id: true,
          },
        },

        product: {
          select: {
            id: true,
          },
        },

        rentPrice: true,
        sourcedFrom: true,

        supplier: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        warehouse: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProductOrder",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProductOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ProductOrderWhereUniqueInput
  ): Promise<ProductOrder | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        itemCount: true,

        jobsite: {
          select: {
            id: true,
          },
        },

        order: {
          select: {
            id: true,
          },
        },

        product: {
          select: {
            id: true,
          },
        },

        rentPrice: true,
        sourcedFrom: true,

        supplier: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        warehouse: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProductOrder",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProductOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ProductOrderWhereUniqueInput,
    @common.Body() data: ProductOrderUpdateInput
  ): Promise<ProductOrder | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          jobsite: data.jobsite
            ? {
                connect: data.jobsite,
              }
            : undefined,

          order: data.order
            ? {
                connect: data.order,
              }
            : undefined,

          product: data.product
            ? {
                connect: data.product,
              }
            : undefined,

          supplier: data.supplier
            ? {
                connect: data.supplier,
              }
            : undefined,

          warehouse: data.warehouse
            ? {
                connect: data.warehouse,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          itemCount: true,

          jobsite: {
            select: {
              id: true,
            },
          },

          order: {
            select: {
              id: true,
            },
          },

          product: {
            select: {
              id: true,
            },
          },

          rentPrice: true,
          sourcedFrom: true,

          supplier: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          warehouse: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "ProductOrder",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProductOrder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ProductOrderWhereUniqueInput
  ): Promise<ProductOrder | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          itemCount: true,

          jobsite: {
            select: {
              id: true,
            },
          },

          order: {
            select: {
              id: true,
            },
          },

          product: {
            select: {
              id: true,
            },
          },

          rentPrice: true,
          sourcedFrom: true,

          supplier: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          warehouse: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "OrderTrack",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/orderTracks")
  @ApiNestedQuery(OrderTrackFindManyArgs)
  async findManyOrderTracks(
    @common.Req() request: Request,
    @common.Param() params: ProductOrderWhereUniqueInput
  ): Promise<OrderTrack[]> {
    const query = plainToClass(OrderTrackFindManyArgs, request.query);
    const results = await this.service.findOrderTracks(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        productOrder: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "ProductOrder",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/orderTracks")
  async connectOrderTracks(
    @common.Param() params: ProductOrderWhereUniqueInput,
    @common.Body() body: OrderTrackWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orderTracks: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "ProductOrder",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/orderTracks")
  async updateOrderTracks(
    @common.Param() params: ProductOrderWhereUniqueInput,
    @common.Body() body: OrderTrackWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orderTracks: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "ProductOrder",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/orderTracks")
  async disconnectOrderTracks(
    @common.Param() params: ProductOrderWhereUniqueInput,
    @common.Body() body: OrderTrackWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orderTracks: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
