/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProductSupplyService } from "../productSupply.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProductSupplyCreateInput } from "./ProductSupplyCreateInput";
import { ProductSupplyWhereInput } from "./ProductSupplyWhereInput";
import { ProductSupplyWhereUniqueInput } from "./ProductSupplyWhereUniqueInput";
import { ProductSupplyFindManyArgs } from "./ProductSupplyFindManyArgs";
import { ProductSupplyUpdateInput } from "./ProductSupplyUpdateInput";
import { ProductSupply } from "./ProductSupply";
import { SupplyTrackFindManyArgs } from "../../supplyTrack/base/SupplyTrackFindManyArgs";
import { SupplyTrack } from "../../supplyTrack/base/SupplyTrack";
import { SupplyTrackWhereUniqueInput } from "../../supplyTrack/base/SupplyTrackWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProductSupplyControllerBase {
  constructor(
    protected readonly service: ProductSupplyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProductSupply",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProductSupply })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: ProductSupplyCreateInput
  ): Promise<ProductSupply> {
    return await this.service.create({
      data: {
        ...data,

        product: data.product
          ? {
              connect: data.product,
            }
          : undefined,

        supplier: data.supplier
          ? {
              connect: data.supplier,
            }
          : undefined,

        supply: data.supply
          ? {
              connect: data.supply,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        price: true,

        product: {
          select: {
            id: true,
          },
        },

        productCount: true,

        supplier: {
          select: {
            id: true,
          },
        },

        supply: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProductSupply",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProductSupply] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ProductSupplyFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<ProductSupply[]> {
    const args = plainToClass(ProductSupplyFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        price: true,

        product: {
          select: {
            id: true,
          },
        },

        productCount: true,

        supplier: {
          select: {
            id: true,
          },
        },

        supply: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProductSupply",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProductSupply })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ProductSupplyWhereUniqueInput
  ): Promise<ProductSupply | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        price: true,

        product: {
          select: {
            id: true,
          },
        },

        productCount: true,

        supplier: {
          select: {
            id: true,
          },
        },

        supply: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProductSupply",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProductSupply })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ProductSupplyWhereUniqueInput,
    @common.Body() data: ProductSupplyUpdateInput
  ): Promise<ProductSupply | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          product: data.product
            ? {
                connect: data.product,
              }
            : undefined,

          supplier: data.supplier
            ? {
                connect: data.supplier,
              }
            : undefined,

          supply: data.supply
            ? {
                connect: data.supply,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          price: true,

          product: {
            select: {
              id: true,
            },
          },

          productCount: true,

          supplier: {
            select: {
              id: true,
            },
          },

          supply: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "ProductSupply",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProductSupply })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ProductSupplyWhereUniqueInput
  ): Promise<ProductSupply | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          price: true,

          product: {
            select: {
              id: true,
            },
          },

          productCount: true,

          supplier: {
            select: {
              id: true,
            },
          },

          supply: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "SupplyTrack",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/supplyTracks")
  @ApiNestedQuery(SupplyTrackFindManyArgs)
  async findManySupplyTracks(
    @common.Req() request: Request,
    @common.Param() params: ProductSupplyWhereUniqueInput
  ): Promise<SupplyTrack[]> {
    const query = plainToClass(SupplyTrackFindManyArgs, request.query);
    const results = await this.service.findSupplyTracks(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        productsupply: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "ProductSupply",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/supplyTracks")
  async connectSupplyTracks(
    @common.Param() params: ProductSupplyWhereUniqueInput,
    @common.Body() body: SupplyTrackWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supplyTracks: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "ProductSupply",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/supplyTracks")
  async updateSupplyTracks(
    @common.Param() params: ProductSupplyWhereUniqueInput,
    @common.Body() body: SupplyTrackWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supplyTracks: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "ProductSupply",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/supplyTracks")
  async disconnectSupplyTracks(
    @common.Param() params: ProductSupplyWhereUniqueInput,
    @common.Body() body: SupplyTrackWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supplyTracks: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
