/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsNumber, IsOptional, ValidateNested, IsInt } from "class-validator";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";
import { Type } from "class-transformer";
import { SupplierWhereUniqueInput } from "../../supplier/base/SupplierWhereUniqueInput";
import { SupplyWhereUniqueInput } from "../../supply/base/SupplyWhereUniqueInput";
import { SupplyTrackUpdateManyWithoutProductSuppliesInput } from "./SupplyTrackUpdateManyWithoutProductSuppliesInput";
@InputType()
class ProductSupplyUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: () => ProductWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProductWhereUniqueInput)
  @IsOptional()
  @Field(() => ProductWhereUniqueInput, {
    nullable: true,
  })
  product?: ProductWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  productCount?: number | null;

  @ApiProperty({
    required: false,
    type: () => SupplierWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SupplierWhereUniqueInput)
  @IsOptional()
  @Field(() => SupplierWhereUniqueInput, {
    nullable: true,
  })
  supplier?: SupplierWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => SupplyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SupplyWhereUniqueInput)
  @IsOptional()
  @Field(() => SupplyWhereUniqueInput, {
    nullable: true,
  })
  supply?: SupplyWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => SupplyTrackUpdateManyWithoutProductSuppliesInput,
  })
  @ValidateNested()
  @Type(() => SupplyTrackUpdateManyWithoutProductSuppliesInput)
  @IsOptional()
  @Field(() => SupplyTrackUpdateManyWithoutProductSuppliesInput, {
    nullable: true,
  })
  supplyTracks?: SupplyTrackUpdateManyWithoutProductSuppliesInput;
}
export { ProductSupplyUpdateInput };
