/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { ProductOrderCreateNestedManyWithoutWarehousesInput } from "./ProductOrderCreateNestedManyWithoutWarehousesInput";
import { Type } from "class-transformer";
import { ProductStockCreateNestedManyWithoutWarehousesInput } from "./ProductStockCreateNestedManyWithoutWarehousesInput";
import { SupplyCreateNestedManyWithoutWarehousesInput } from "./SupplyCreateNestedManyWithoutWarehousesInput";
@InputType()
class WarehouseCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProductOrderCreateNestedManyWithoutWarehousesInput,
  })
  @ValidateNested()
  @Type(() => ProductOrderCreateNestedManyWithoutWarehousesInput)
  @IsOptional()
  @Field(() => ProductOrderCreateNestedManyWithoutWarehousesInput, {
    nullable: true,
  })
  productOrders?: ProductOrderCreateNestedManyWithoutWarehousesInput;

  @ApiProperty({
    required: false,
    type: () => ProductStockCreateNestedManyWithoutWarehousesInput,
  })
  @ValidateNested()
  @Type(() => ProductStockCreateNestedManyWithoutWarehousesInput)
  @IsOptional()
  @Field(() => ProductStockCreateNestedManyWithoutWarehousesInput, {
    nullable: true,
  })
  productStocks?: ProductStockCreateNestedManyWithoutWarehousesInput;

  @ApiProperty({
    required: false,
    type: () => SupplyCreateNestedManyWithoutWarehousesInput,
  })
  @ValidateNested()
  @Type(() => SupplyCreateNestedManyWithoutWarehousesInput)
  @IsOptional()
  @Field(() => SupplyCreateNestedManyWithoutWarehousesInput, {
    nullable: true,
  })
  supplies?: SupplyCreateNestedManyWithoutWarehousesInput;
}
export { WarehouseCreateInput };
