/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ManufacturerWhereUniqueInput } from "../../manufacturer/base/ManufacturerWhereUniqueInput";
import { ValidateNested, IsString, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { ProductOrderCreateNestedManyWithoutProductsInput } from "./ProductOrderCreateNestedManyWithoutProductsInput";
import { ProductStockCreateNestedManyWithoutProductsInput } from "./ProductStockCreateNestedManyWithoutProductsInput";
import { ProductSupplyCreateNestedManyWithoutProductsInput } from "./ProductSupplyCreateNestedManyWithoutProductsInput";
@InputType()
class ProductCreateInput {
  @ApiProperty({
    required: true,
    type: () => ManufacturerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ManufacturerWhereUniqueInput)
  @Field(() => ManufacturerWhereUniqueInput)
  manufacturer!: ManufacturerWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProductOrderCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ProductOrderCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ProductOrderCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  productOrders?: ProductOrderCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => ProductStockCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ProductStockCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ProductStockCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  productStocks?: ProductStockCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => ProductSupplyCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ProductSupplyCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ProductSupplyCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  productSupplies?: ProductSupplyCreateNestedManyWithoutProductsInput;
}
export { ProductCreateInput };
