/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { ManufacturerWhereUniqueInput } from "../../manufacturer/base/ManufacturerWhereUniqueInput";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { ProductOrderListRelationFilter } from "../../productOrder/base/ProductOrderListRelationFilter";
import { ProductStockListRelationFilter } from "../../productStock/base/ProductStockListRelationFilter";
import { ProductSupplyListRelationFilter } from "../../productSupply/base/ProductSupplyListRelationFilter";
@InputType()
class ProductWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => ManufacturerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ManufacturerWhereUniqueInput)
  @IsOptional()
  @Field(() => ManufacturerWhereUniqueInput, {
    nullable: true,
  })
  manufacturer?: ManufacturerWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ProductOrderListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ProductOrderListRelationFilter)
  @IsOptional()
  @Field(() => ProductOrderListRelationFilter, {
    nullable: true,
  })
  productOrders?: ProductOrderListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ProductStockListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ProductStockListRelationFilter)
  @IsOptional()
  @Field(() => ProductStockListRelationFilter, {
    nullable: true,
  })
  productStocks?: ProductStockListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ProductSupplyListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ProductSupplyListRelationFilter)
  @IsOptional()
  @Field(() => ProductSupplyListRelationFilter, {
    nullable: true,
  })
  productSupplies?: ProductSupplyListRelationFilter;
}
export { ProductWhereInput };
